### ISSUE TITLE
Implement TMD generation when packing a CIA.

### ISSUE THREAD

**Issue by WorstAquaPlayer** [SceneGate/Lemon#13]
**Is your feature request related to a problem? Please describe.**
As mentioned in #12, generating a new CIA binary with modified content will not work properly. (Maybe it works in emulator by luck, but not on a real console).

**Describe the solution you'd like**
When using `NodeContainer2BinaryCia`, it should create a new TMD by reading the original file to get information like the content info and content chunks and use it to create a new TMD.

Proposed plan of implementation (same or different PRs):

- Create two new properties in the `TitleMetadata` class and read them when using `Binary2TitleMetadata`, the sign type and the sign size.
- When using `NodeContainer2BinaryCia`, instead of writing the binary of the `"title"` child, it would create and write a new one by using the `TitleMetadata` properties and by reading some information from the original binary (content info records).

**Describe alternatives you've considered**
I thought of making more properties to the `TitleMetadata` class, but that would be hard to make since some relies on hashes and the content info records are long.

**Additional context**
I have some working code that goes with my proposed plan of implementation. If this is okay, then I'll make a pull request.

**Comment by pleonex** [comment]
I agree. However I think it would be better if we update the `title` node content, so after using `NodeContainer2BinaryCia` we have the new TMD there.

I think we should create first a `TitleMetadata2Binary` converter (#14). Then in this request we can update the CIA converter to update the TMD and use the new TMD converter to write it to binary before writing it inside the CIA.

Is that ok?

**Comment by WorstAquaPlayer** [comment]
The thing is, starting from 0xA4, the TMD has hashes of sections that could change at any time and are written after the hashes So, I don't know if it's possible, but maybe adding the `TitleMetadata2Binary` converter which needs the chunks as arguments to properly convert them?

**Comment by pleonex** [comment]
The `TitleMetadata` class already has [a property](https://github.com/SceneGate/Lemon/blob/develop/src/Lemon/Titles/TitleMetadata.cs#L117) with the [record class](https://github.com/SceneGate/Lemon/blob/develop/src/Lemon/Titles/ContentChunkRecord.cs) that contains the hashes.

So the idea could be that the CIA converter updates the TMD records, including the hashes, and then it calls the `TitleMetadata2Binary`. Would that work?

**Comment by WorstAquaPlayer** [comment]
Yeah, that would work. But to be faithful to the original TMD and to avoid reading the original one in the `NodeContainer2BinaryCia` converter, a new class (`ContentInfoRecord`, which contains the properties `short IndexOffset`, `short CommandCount` and `byte[] Hash`) would be created, and would be populated when reading the CIA, so when writing the updated TMD it uses the original info record data (except the hashes). Is that a little overkill?

**Comment by pleonex** [comment]
I think the class you mentioned already exists, right? https://github.com/SceneGate/Lemon/blob/develop/src/Lemon/Titles/ContentChunkRecord.cs
It's part of the `TitleMetadata` class: https://github.com/SceneGate/Lemon/blob/develop/src/Lemon/Titles/TitleMetadata.cs#L117

I think we should read the node if it's in binary format to get the information and to avoid duplicating the same information in several classes. This would be my proposal logic for the `NodeContainer2BinaryCia` converter:

1. Check the format of the node `title`. If it's `BinaryFormat`, then use `Binary2TitleMetadata` to read it.
2. Update the hashes and size of the chunk records of the `title` format node.
3. Use `TitleMetadata2Binary` to convert the `title` node into binary format (#14)
4. Write the `title` node to the CIA with the rest of nodes.

I think this could be a good solution for now, if you agree.

In the future, once we have all the converters, I was thinking to create a class like `GameBuilder`, similar to [ContainerManager](https://github.com/SceneGate/Lemon/blob/develop/src/Lemon/Containers/ContainerManager.cs), that will go from nodes to the final CIA/.3ds. It will ensure all the required files exists, update the information (like TMD) and call in sequence all the converters to pack the ExeFs, RomFS, NCCH, TMD and finally CIA. But that's a refactor we could do later, and requires some more thinking.

**Comment by WorstAquaPlayer** [comment]
> I think the class you mentioned already exists, right? https://github.com/SceneGate/Lemon/blob/develop/src/Lemon/Titles/ContentChunkRecord.cs It's part of the `TitleMetadata` class: https://github.com/SceneGate/Lemon/blob/develop/src/Lemon/Titles/TitleMetadata.cs#L117

No, the class I mean would recollect information from the [Content Info Records](https://www.3dbrew.org/wiki/Title_metadata), not the Content Chunk Records (since its class already exists).

I like the proposition of the converter, but would like to see your word in the Content Info Records thing.

**Comment by pleonex** [comment]
You are right, I totally forgot about that structure. I was confused by the names... Sorry about that.

We will need to add that class into `TitleMetadata` with the hashes. Then, the converter `TitleMetadata2Binary` could update the hashes in _Content Info Records_ (from the written bytes of _chunk records_) before writing it.
