### ISSUE TITLE
Update documentation of required nodes for NCCH converter

### ISSUE THREAD

**Issue by WorstAquaPlayer** [SceneGate/Lemon#17]
The file [Ncch2Binary.cs (line 39 to 41)](https://github.com/SceneGate/Lemon/blob/develop/src/Lemon/Containers/Converters/Ncch2Binary.cs#L39)
mentions that it expects nodes that are in "header_data", this is a leftover of when I tried to make all the header data nodes.
Small thing, but I forgot to remove it.

**Comment by pleonex** [comment]
No problem, we can update the comment in the next pull request. Thanks for taking a note.
