### ISSUE TITLE
Implement NCCH packing

### ISSUE THREAD

**Issue by pleonex** [SceneGate/Lemon#8]
**Description**
Implement a converter to pack/write nodes into the binary format [`NCCH`](https://www.3dbrew.org/wiki/NCCH).

**Describe the solution you'd like**
Create a new class `Ncch2Binary` that implements `IConverter<NodeContainerFormat, BinaryFormat>`. The input `NodeContainerFormat` should have a specific folder hierarchy, like a node with the format `NcchHeader`.

Proposed plan of implementation (same or different PRs):
- [x] Read the remaining of the `NCHH` header in `Binary2Ncch` (the TODOs).
- [x] Implement integration test.
- [x] Implement `Ncch2Binary` converter.

**Describe alternatives you've considered**
The current approach of having the header as part of the property class instead of as a specific node. However, it would be harder for generic tools to display the header and being a separate node can simplify potential future converters into yaml or binary.

**Additional context**
Tests should be implemented in `NcchConverterTests` and they should verify that we generate back and forward the exactly same binary. We would need to add one new test that does something like this:

```csharp
using var nodes = containerConverter.Convert(original);
using var actualBinary = binaryConverter.Convert(nodes);
Assert.That(original.Stream.Compare(actualBinary.Stream), Is.True, "Streams are not identical");
```

**Comment by WorstAquaPlayer** [comment]
Hi! I want to contribute to resolve this issue. Something I want to say first is that I read the Yarhl contributing guidelines and I don't know if I have to make a new issue or just comment on this existing one of the same topic. Either way, I guess I could just comment what I have to say and copy paste it in an issue if that's necessary.
I wanted to ask if progress on this has been made. If the answer is no, I would like to make a new Pull Request that will resolve this issue.

**Comment by pleonex** [comment]
Hi and thanks for taking your time! You can comment on this issue to do the implementation of the NCCH packing, no need to create a new one. I have updated the description to add more details about the proposed design and work to do.

I didn't start with this yet, so you can go ahead 😄 
If you have any question feel free to add a comment in this issue, create a GitHub discussion or contact us via Discord.

**Comment by WorstAquaPlayer** [comment]
Thanks for answering my questions kindly.
I have started an implementation, and it is similar to what you proposed, the difference being that I didn't make the header a child node.
So, should I make a pull request or not yet? (Sorry if these questions are dumb, my brain doesn't fully understand the contribution guideline lol)

**Comment by pleonex** [comment]
No problem, we can move the header into a node later in a separate PR.
You can create the pull request and we can discuss the implementation there. Thanks!

(I need to update the contribution guidelines, they are a bit old).
